#!/bin/bash

PHRASES=("NIGGALISHOUS K" "TOGO NIGGA" "DAMN I'VE GOT TO LEARN CIRCUITS")

RANDOM_INDEX=$(( RANDOM % ${#PHRASES [@]}))

SELECTED_PHRASE=${PHRASES[$RANDOM_INDEX]}

figlet -w 200 -f starwars "$SELECTED_PHRASE"